basePath: /api/v1
definitions:
  model.TodoModel:
    properties:
      completed:
        example: false
        type: boolean
      description:
        example: Milk, eggs, bread
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Buy groceries
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple API for managing TODOs.
  title: TODO API2
  version: 0.0.1
paths:
  /todos:
    get:
      description: get todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TodoModel'
            type: array
      summary: Get all todos
      tags:
      - Todos
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.n
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
